//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contacts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageUa {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageUa() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Contacts.LanguageUa", typeof(LanguageUa).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати зображення.
        /// </summary>
        internal static string ActionSheetTextAddPhoto {
            get {
                return ResourceManager.GetString("ActionSheetTextAddPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невірний логін.
        /// </summary>
        internal static string AlertHeaderInvalidLogin {
            get {
                return ResourceManager.GetString("AlertHeaderInvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невірний пароль.
        /// </summary>
        internal static string AlertHeaderInvalidPassword {
            get {
                return ResourceManager.GetString("AlertHeaderInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увага.
        /// </summary>
        internal static string AlertHederInvalidPOL {
            get {
                return ResourceManager.GetString("AlertHederInvalidPOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалити цей профіль?.
        /// </summary>
        internal static string AlertTextDeleteProfiles {
            get {
                return ResourceManager.GetString("AlertTextDeleteProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильний логін або пароль.
        /// </summary>
        internal static string AlertTextInvalidPOL {
            get {
                return ResourceManager.GetString("AlertTextInvalidPOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш логін має містити більше 4 символів і менше 16 символів!.
        /// </summary>
        internal static string AlertTextLemitLogin {
            get {
                return ResourceManager.GetString("AlertTextLemitLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логін не повинен починатися з номера!.
        /// </summary>
        internal static string AlertTextLoginNum {
            get {
                return ResourceManager.GetString("AlertTextLoginNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш пароль не співпадає!.
        /// </summary>
        internal static string AlertTextPasswordDifferent {
            get {
                return ResourceManager.GetString("AlertTextPasswordDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш пароль має містити більше 8 символів і менше 16 символів!.
        /// </summary>
        internal static string AlertTextPasswordValid {
            get {
                return ResourceManager.GetString("AlertTextPasswordValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to УВІЙТИ.
        /// </summary>
        internal static string ButtonSignIn {
            get {
                return ResourceManager.GetString("ButtonSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЗАРЕЄСТРУВАТИСЯ.
        /// </summary>
        internal static string ButtonSignUp {
            get {
                return ResourceManager.GetString("ButtonSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати профіль.
        /// </summary>
        internal static string HederAddProfile {
            get {
                return ResourceManager.GetString("HederAddProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Змінити профіль.
        /// </summary>
        internal static string HederEditProfile {
            get {
                return ResourceManager.GetString("HederEditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Головний список.
        /// </summary>
        internal static string HederMainList {
            get {
                return ResourceManager.GetString("HederMainList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Налаштування.
        /// </summary>
        internal static string HederSetting {
            get {
                return ResourceManager.GetString("HederSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вхід користувача.
        /// </summary>
        internal static string HederSignIn {
            get {
                return ResourceManager.GetString("HederSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реєстрація Користувача.
        /// </summary>
        internal static string HederSignUp {
            get {
                return ResourceManager.GetString("HederSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За датою.
        /// </summary>
        internal static string LabelByDate {
            get {
                return ResourceManager.GetString("LabelByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За ім&apos;ям.
        /// </summary>
        internal static string LabelByName {
            get {
                return ResourceManager.GetString("LabelByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За псевдонімом.
        /// </summary>
        internal static string LabelByNickName {
            get {
                return ResourceManager.GetString("LabelByNickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Темна.
        /// </summary>
        internal static string LabelDark {
            get {
                return ResourceManager.GetString("LabelDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мова.
        /// </summary>
        internal static string LabelLanguage {
            get {
                return ResourceManager.GetString("LabelLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Світла.
        /// </summary>
        internal static string LabelLight {
            get {
                return ResourceManager.GetString("LabelLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не додано жодного профілю. .
        /// </summary>
        internal static string LabelNoProfiles {
            get {
                return ResourceManager.GetString("LabelNoProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сортувати.
        /// </summary>
        internal static string LabelSort {
            get {
                return ResourceManager.GetString("LabelSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тема.
        /// </summary>
        internal static string LabelThem {
            get {
                return ResourceManager.GetString("LabelThem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підтвердьте пароль.
        /// </summary>
        internal static string PlaceholderConfirmPassword {
            get {
                return ResourceManager.GetString("PlaceholderConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опис.
        /// </summary>
        internal static string PlaceholderDescription {
            get {
                return ResourceManager.GetString("PlaceholderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логін.
        /// </summary>
        internal static string PlaceholderLogin {
            get {
                return ResourceManager.GetString("PlaceholderLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ім&apos;я.
        /// </summary>
        internal static string PlaceholderName {
            get {
                return ResourceManager.GetString("PlaceholderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Псевдонім.
        /// </summary>
        internal static string PlaceholderNickName {
            get {
                return ResourceManager.GetString("PlaceholderNickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        internal static string PlaceholderPassword {
            get {
                return ResourceManager.GetString("PlaceholderPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЗАРЕЄСТРУВАТИСЯ.
        /// </summary>
        internal static string RefSignUp {
            get {
                return ResourceManager.GetString("RefSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скасувати.
        /// </summary>
        internal static string TextCancel {
            get {
                return ResourceManager.GetString("TextCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Галерея.
        /// </summary>
        internal static string TextGallery {
            get {
                return ResourceManager.GetString("TextGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зробити фото.
        /// </summary>
        internal static string TextTakeAPhoto {
            get {
                return ResourceManager.GetString("TextTakeAPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Так.
        /// </summary>
        internal static string TextYes {
            get {
                return ResourceManager.GetString("TextYes", resourceCulture);
            }
        }
    }
}
