//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contacts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageEn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageEn() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Contacts.LanguageEn", typeof(LanguageEn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add photo.
        /// </summary>
        internal static string ActionSheetTextAddPhoto {
            get {
                return ResourceManager.GetString("ActionSheetTextAddPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login.
        /// </summary>
        internal static string AlertHeaderInvalidLogin {
            get {
                return ResourceManager.GetString("AlertHeaderInvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password.
        /// </summary>
        internal static string AlertHeaderInvalidPassword {
            get {
                return ResourceManager.GetString("AlertHeaderInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string AlertHederInvalidPOL {
            get {
                return ResourceManager.GetString("AlertHederInvalidPOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this profile?.
        /// </summary>
        internal static string AlertTextDeleteProfiles {
            get {
                return ResourceManager.GetString("AlertTextDeleteProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login or password!.
        /// </summary>
        internal static string AlertTextInvalidPOL {
            get {
                return ResourceManager.GetString("AlertTextInvalidPOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your login must be more than 4 characters and less than 16 characters!.
        /// </summary>
        internal static string AlertTextLemitLogin {
            get {
                return ResourceManager.GetString("AlertTextLemitLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login must not start with a number!.
        /// </summary>
        internal static string AlertTextLoginNum {
            get {
                return ResourceManager.GetString("AlertTextLoginNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password mismatch!.
        /// </summary>
        internal static string AlertTextPasswordDifferent {
            get {
                return ResourceManager.GetString("AlertTextPasswordDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password must be more than 8 characters and less than 16 characters!.
        /// </summary>
        internal static string AlertTextPasswordValid {
            get {
                return ResourceManager.GetString("AlertTextPasswordValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN IN.
        /// </summary>
        internal static string ButtonSignIn {
            get {
                return ResourceManager.GetString("ButtonSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN UP.
        /// </summary>
        internal static string ButtonSignUp {
            get {
                return ResourceManager.GetString("ButtonSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddProfile.
        /// </summary>
        internal static string HederAddProfile {
            get {
                return ResourceManager.GetString("HederAddProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditProfile.
        /// </summary>
        internal static string HederEditProfile {
            get {
                return ResourceManager.GetString("HederEditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main List.
        /// </summary>
        internal static string HederMainList {
            get {
                return ResourceManager.GetString("HederMainList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string HederSetting {
            get {
                return ResourceManager.GetString("HederSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User SignIn.
        /// </summary>
        internal static string HederSignIn {
            get {
                return ResourceManager.GetString("HederSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users SignUp.
        /// </summary>
        internal static string HederSignUp {
            get {
                return ResourceManager.GetString("HederSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By date.
        /// </summary>
        internal static string LabelByDate {
            get {
                return ResourceManager.GetString("LabelByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Name.
        /// </summary>
        internal static string LabelByName {
            get {
                return ResourceManager.GetString("LabelByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By NickName.
        /// </summary>
        internal static string LabelByNickName {
            get {
                return ResourceManager.GetString("LabelByNickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string LabelDark {
            get {
                return ResourceManager.GetString("LabelDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string LabelLanguage {
            get {
                return ResourceManager.GetString("LabelLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string LabelLight {
            get {
                return ResourceManager.GetString("LabelLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No profiles added..
        /// </summary>
        internal static string LabelNoProfiles {
            get {
                return ResourceManager.GetString("LabelNoProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        internal static string LabelSort {
            get {
                return ResourceManager.GetString("LabelSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Them.
        /// </summary>
        internal static string LabelThem {
            get {
                return ResourceManager.GetString("LabelThem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string PlaceholderConfirmPassword {
            get {
                return ResourceManager.GetString("PlaceholderConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string PlaceholderDescription {
            get {
                return ResourceManager.GetString("PlaceholderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string PlaceholderLogin {
            get {
                return ResourceManager.GetString("PlaceholderLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string PlaceholderName {
            get {
                return ResourceManager.GetString("PlaceholderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NickName.
        /// </summary>
        internal static string PlaceholderNickName {
            get {
                return ResourceManager.GetString("PlaceholderNickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PlaceholderPassword {
            get {
                return ResourceManager.GetString("PlaceholderPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN UP.
        /// </summary>
        internal static string RefSignUp {
            get {
                return ResourceManager.GetString("RefSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string TextCancel {
            get {
                return ResourceManager.GetString("TextCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        internal static string TextGallery {
            get {
                return ResourceManager.GetString("TextGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a photo.
        /// </summary>
        internal static string TextTakeAPhoto {
            get {
                return ResourceManager.GetString("TextTakeAPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string TextYes {
            get {
                return ResourceManager.GetString("TextYes", resourceCulture);
            }
        }
    }
}
